services:
  webstore:
    container_name: webstore
    build: .
    ports:
      - "8080:80"
    user: "1000:1000"
    volumes:
      - ./html:/var/www/html
      - ./store:/store
    restart: unless-stopped
