services:
  webstore:
    container_name: webstore
    build: .
    ports:
      - "${PORT:-8080}:80"
    user: "1000:1000"
    volumes:
      - store:/store
    restart: unless-stopped

volumes:
  store:
